config/routes.rb
Rails.application.routes.draw do
  root 'questions#new'

  get 'admin/register', to: 'admins#new'
  post 'admin/register', to: 'admins#create'
  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'
  delete 'admin/logout', to: 'sessions#destroy'
  resources :questions, param: :token
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  validates :name, presence: true, length: { maximum: 18 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

require 'securerandom'

class Question < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  before_create :generate_token

  has_one_attached :img

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end
end

app/controllers/admins_controller.rb
# frozen_string_literal: true

class AdminsController < ApplicationController
  include AdminsHelper

  before_action :only_one_admin, only: %i[new create]

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_param)
    if @admin.save
      log_in @admin
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def only_one_admin
    redirect_to admin_login_path if admin_exist?
  end

  def admin_param
    params.require(:admin).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsHelper
  include AdminsHelper

  before_action :only_admin, only: %i[update edit destroy]

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_url(token: @question.token)
    else
      render 'new'
    end
  end

  def show
    @question = Question.find_by(token: params[:token])
    render_raw unless params[:raw].nil?
    render_404 if @question.nil?
    @tweet_url = tweet_url

    set_meta_info @question
  end

  def index
    @question  = Question.new
    if logged_in?
      @questions = Question.all
    else
      @questions = Question.where.not(replay: nil)
    end
  end

  def edit
    @question = Question.find_by(token: params[:token])
    create_image(@question) unless @question.img.attached?
  end

  def destroy
    Question.find_by(token: params[:token])&.destroy
    redirect_to questions_url
  end

  def update
    @question = Question.find_by(token: params[:token])

    if @question.update_attributes(question_params)
      redirect_to question_url(token: @question.token)
    else
      render 'edit'
    end
  end

  private

  def only_admin
    redirect_to question_url(token: params[:token]) unless logged_in?
  end

  def question_params
    params.require(:question).permit(:content, :replay)
  end

  def render_raw
    render template: 'questions/raw', status: 200, layout: false, content_type: 'text/html'
  end

  def tweet_url
    URI.encode("http://twitter.com/intent/tweet?original_referer=#{question_url(token: @question.token)}&url=#{question_url(token: @question.token)}&text=#{@question.replay}")
  end

  def set_meta_info(q)
    set_meta_tags description: q.content
    set_meta_tags og: {
                    title: "Q box",
                    site_name: "#{admin_user.name} Q box",
                    description: q.content,
                    url: question_url(token: params[:token]),
                    type: "website"
                  }
    set_meta_tags twitter: {
                    card: "summary_large_image",
                    site: "@takuchalle"
                  }
    set_meta_tags og: { image: url_for(q.img) } if q.img.attached?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include AdminsHelper

  before_action :need_register?, only: %i[new create destroy]

  def new; end

  def create
    @admin = Admin.first
    if @admin&.authenticate(params[:session][:password])
      log_in @admin
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  private

  def need_register?
    redirect_to admin_register_path unless admin_exist?
  end
end

app/helpers/admins_helper.rb
# frozen_string_literal: true

module AdminsHelper
  def admin_user
    Admin.first
  end

  def admin_exist?
    !admin_user.nil?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questions_helper.rb
# coding: utf-8
# frozen_string_literal: true

module QuestionsHelper
  def create_image(q)
    Tempfile.create(["#{q.token}", '.png'], :encoding => 'ascii-8bit') do | file |
      file.write(IMGKit.new(get_html(q.content), quality: 20, width: 800).to_png)
      file.rewind
      q.img.attach(io: file, filename: "q_#{q.id}.png", content_type: "image/png")
    end
  end

  def get_html(body)
    <<~HTML
    <!DOCTYPE html>
<html lang="ja">
  <head>
	<meta charset="UTF-8">
	<style>
	  @charset "UTF-8";
	  html {
		  font-family: sans-serif;
		  -ms-text-size-adjust: 100%;
		  -webkit-text-size-adjust: 100%;
	  }
	  body {
		  width: 800px;
		  margin: 0;
	  }
	  .q-frame {
		  width: 100%;
		  background-color: #FA514B;
		  padding: 25px 25px 10px 25px;
	  }
	  .q-frame .q-body {
          vertical-align: middle;
          text-align: center;
          min-height: 250px;
		  font-size: 2.6em;
		  background-color: white;
		  padding: 1.3em;
		  border-radius: 5px;
	  }
	  .q-frame .q-icon {
		  font-size: 2.2em;
		  padding: 5px 0px 0px 0px;
		  margin: 0px;
		  color: white;
		  border-radius: 5px;
	  }
	</style>
  </head>
  <body>
	<div class="q-frame">
	  <div class="q-body">
		#{body}
	  </div>
	  <div class="q-icon">
		Q Box
	  </div>
	</div>
  </body>
</html>
    HTML
  end

end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(admin)
    session[:admin_id] = admin.id
  end

  def log_out
    session.delete(:admin_id)
    @logged_in_user = nil
  end

  def logged_in_user
    if (admin_id = session[:admin_id])
      @logged_in_user ||= Admin.find_by(id: admin_id)
    else
      @logged_in_user = nil
    end
  end

  def logged_in?
    !logged_in_user.nil?
  end
end

app/views/admins/new.html.erb
<div class="admin_register">
  <h1>管理者登録</h1>

  <%= form_for(:admin, url:admin_register_path) do |f| %>

  <%= f.label '名前' %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label 'パスワード' %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label 'パスワード確認' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit '登録', class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
	<%= link_to 'トップページ', root_path %>
	<% if logged_in? %>
	<div>
	  <%= link_to 'ログアウト', admin_logout_path, method: :delete %>
	</div>
	<% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
	<div class="header-inner">
	  <div class="logo">
		<%= link_to 'Q Box', root_path %>
	  </div>
	</div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qbox</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

	<%= display_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	<div class="container">
	  <%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/questions/_content_form.html.erb
<div class="content-form">
  <%= form_for(@question) do |f| %>
  <%= f.text_area :content, placeholder: "ask me anything..." %>
  <%= f.submit "Ask", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/questions/_question.html.erb
<li class="question-li">
  <div class="question">
	<div class="date">
	  <%= question.created_at.strftime('%Y/%m/%d') %>
	</div>
	<div class="content">
	  <%= question.content %>
	</div>
	<% unless question.replay.nil? %>
	<%= link_to '回答を見る', question_path(token: question.token) %>
	<% end %>
	<% if logged_in? %>
	<div class="edit">
	  <div class="delete">
		<%= link_to '削除', question_path(token: question.token), method: :delete %>
	  </div>
	  <div class="replay">
		<%= link_to '返信', edit_question_path(token: question.token) %>
	  </div>
	</div>
	<% end %>
  </div>
</li>

app/views/questions/edit.html.erb
<%= render @question %>

<%= form_for(@question, url: question_url(token: @question.token)) do |f| %>
<%= f.text_area :replay, placeholder: "reolay...", class: "content-form" %>
<%= f.submit "Replay", class: "btn btn-primary" %>
<% end %>

app/views/questions/index.html.erb
<h1>回答した質問</h1>

<div class="question-list">
  <% if @questions.any? %>
  <%= render @questions %>
  <% else %>
  まだ回答がありません。
  <% end %>
</div>
<div class="">
  <h2><%= "#{admin_user.name}さんに" unless admin_user.nil? %>質問してみよう</h2>

  <%= render 'content_form' %>
</div>

app/views/questions/new.html.erb
<h1><%= "#{admin_user.name}さんに" unless admin_user.nil? %>質問してみよう</h1>

<%= render 'content_form' %>

<%= "#{admin_user.name}さんが" unless admin_user.nil? %>回答した質問は<%= link_to 'こちら', questions_path %>

app/views/questions/raw.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
	<div class="q-frame">
	  <div class="q-body">
		<%= @question.content %>
	  </div>
	  <div class="q-icon">
		Q Box
	  </div>
	</div>
  </body>
</html>

app/views/questions/show.html.erb
<% unless @question.img.attached? %>
ご質問ありがとうございます！！
回答されるまでしばらくお待ち下さい。
<%= render @question %>
<% else %>
<div class="question-image">
  <%= image_tag( @question.img ) %>
</div>

<div class="anser">
  <div class="ans-title">
	回答
  </div>
  <div class="ans-body">
	<%= @question.replay %>
  </div>
</div>
<%= link_to 'この回答をツイートする', @tweet_url %>
<% end %>